# Generated by Django 2.2.6 on 2020-03-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=2)),
                ('country_code_2', models.CharField(max_length=3)),
                ('year', models.IntegerField()),
                ('GDP_growth', models.FloatField()),
            ],
        ),
    ]
