# Generated by Django 2.2.6 on 2020-04-14 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(default=None, max_length=200)),
                ('updated_weight', models.FloatField(default=0.0)),
                ('higher_is_better', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('capital', models.FloatField()),
                ('creation_date', models.DateTimeField(null=True)),
                ('number_of_employees', models.IntegerField(null=True)),
                ('maturity', models.CharField(default='Not specified', max_length=100)),
                ('founder', models.CharField(blank=True, default='', max_length=200)),
                ('customers', models.CharField(blank=True, default='', max_length=200)),
                ('operationals', models.CharField(blank=True, default='', max_length=200)),
                ('market_potential', models.CharField(blank=True, default='', max_length=200)),
                ('investors', models.CharField(blank=True, default='', max_length=200)),
                ('partnerships', models.CharField(blank=True, default='', max_length=200)),
                ('innovation', models.BooleanField(default=False)),
                ('impact', models.BooleanField(default=False)),
                ('awards', models.CharField(blank=True, default='', max_length=400)),
                ('growth_rate', models.FloatField(blank=True, default=None, null=True)),
                ('reported_net_result', models.FloatField(blank=True, default=None, null=True)),
                ('reported_net_debt', models.FloatField(blank=True, default=None, null=True)),
                ('website', models.URLField(default='', null=True)),
                ('presentation', models.TextField(blank=True, default=None)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup.Countries')),
            ],
        ),
        migrations.CreateModel(
            name='StartupSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(default='', max_length=200)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup.Startup')),
            ],
        ),
        migrations.CreateModel(
            name='StartupPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('value', models.FloatField()),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup.Startup')),
            ],
        ),
        migrations.CreateModel(
            name='StartupActivityCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='', max_length=200)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup.Startup')),
            ],
        ),
        migrations.CreateModel(
            name='CountryPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('value', models.FloatField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup.Countries')),
                ('performance_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup.PerformanceIndex')),
            ],
        ),
    ]
