# Generated by Django 2.2.6 on 2020-03-23 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countries',
            name='GDP_growth',
        ),
        migrations.RemoveField(
            model_name='countries',
            name='country_code_2',
        ),
        migrations.RemoveField(
            model_name='countries',
            name='year',
        ),
        migrations.AlterField(
            model_name='countries',
            name='country_code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='countries',
            name='country_name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Capital', models.FloatField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup.Countries')),
            ],
        ),
        migrations.CreateModel(
            name='CountryPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('GDP_growth', models.FloatField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup.Countries')),
            ],
        ),
    ]
