# built by considering only indexes present in more than 40 countries at least in one of the last 3 years
TAKE_INTO_ACCOUNT = {
    'EMPLOYMENT IN SERVICES (% OF TOTAL EMPLOYMENT)': True,
    'EMPLOYMENT TO POPULATION RATIO, AGES 15-24, TOTAL (%)': False,
    'FDI, INWARD, % OF GDP': False,
    'GDP GROWTH (ANNUAL %)': True,
    'GDP PER CAPITA (US$)': True,
    'GDP PER CAPITA GROWTH (ANNUAL %)': True,
    'GDP PER CAPITA, PPP (CURRENT INTERNATIONAL $)': True,
    'GDP PER PERSON EMPLOYED (CONSTANT 1990 PPP $)': True,
    'GDP, REAL USD (MILLIONS)': True,
    'GROSS GOVERNMENT DEBT (% OF GDP)': True,
    'INDUSTRY, VALUE ADDED (% OF GDP)': True,
    'INDUSTRY, VALUE ADDED (US$)': True,
    'INFLATION': False,
    'INFLATION, CONSUMER PRICES (ANNUAL %)': True,
    'LABOR FORCE PARTICIPATION RATE, TOTAL (% OF TOTAL AGES 15-64)': True,
    'LABOR FORCE, TOTAL': True,
    'LIFE EXPECTANCY AT BIRTH, TOTAL (YEARS)': True,
    'LISTED DOMESTIC COMPANIES, TOTAL': False,
    'MOBILE CELLULAR SUBSCRIPTIONS (DATA FROM ITU)': True,
    'MOBILE CELLULAR SUBSCRIPTIONS (PER 100 PEOPLE) (DATA FROM ITU)': False,
    'NET TAXES ON PRODUCTS (US$)': False,
    'POPULATION IN THE LARGEST CITY (% OF URBAN POPULATION)': True,
    'POPULATION, TOTAL': True,
    'TAX REVENUE (% OF GDP)': False,
    'TAX REVENUE, CORPORATE (%YOY)': False,
    'UNEMPLOYMENT': False,
    'UNEMPLOYMENT RATE (%YOY, STANDARDIZED)': False,
    'UNEMPLOYMENT RATE (STANDARDIZED)': False,
    'UNEMPLOYMENT RATE, ILO DEFINITION': True,
    "VENTURE CAPITAL DEALS": True,
    "PRIVATE EQUITY DEALS": True,
}

DEFAULT_STARTUP_FILTERS = {
    1: {"name": "impact", 'chosen': False, "value": 100, "alt": "impact"},
    2: {"name": "innovation", 'chosen': False, "value": 100, 'alt': 'innovation'},
    3: {"name": "awards", "chosen": False, 'value': 100, "alt": "awards"},
    4: {"name": "capital", "chosen": True, "value": 100, "alt": 'capital'},
    5: {"name": "number of employees", "chosen": False, 'value': 20, 'alt': 'number_of_employees'},
    6: {"name": "debt", "chosen": False, "value": 20, 'alt': 'net_debt'},
    7: {"name": 'net result', 'chosen': True, "value": 10, 'alt': 'net_result'},
    8: {"name": "number of founders", 'chosen': True, "value": 20, 'alt': 'founders'},
    9: {"name": "investors", 'chosen': True, "value": 20, 'alt': 'investors'},
    10: {"name": "years since creation", 'chosen': False, "value": 20, 'alt': 'years_since_creation'},
    11: {"name": 'Country performance', 'chosen': True, "value": 100, 'alt': 'country_performance'},
    12: {"name": "Nomber of years with fund raise", 'chosen': False, "value":100, "alt": "nb_fund_raising_years"},
    13: {"name": 'Fund raising value', 'chosen': True, 'value': 100, "alt": 'fund_raising_value'},
    14: {"name": 'Founders mean age (older is better)', 'value': 0, 'chosen': False, "alt": "founders_mean_age_ob"},
    15: {"name": 'Founders mean age (younger is better)', 'value': 0, 'chosen': False, "alt": "founders_mean_age_yb"},
}
